services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: blog_desarrollo 

    command: python manage.py runserver 0.0.0.0:8000

    environment:
      - PYTHONUNBUFFERED=1 
      - DJANGO_SETTINGS_MODULE=config.settings_development # <-- ¡Usar settings_development!

    ports:
      - "8080:8000"

    volumes:
      - .:/app
      - "./db.sqlite3:/app/db.sqlite3"


