# Generated by Django 5.1 on 2025-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, related_name='articulos', to='blog.categoria'),
        ),
    ]
