# Generated by Django 5.1 on 2025-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articulo_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='articulos', to='blog.categoria'),
        ),
    ]
